/****
 * QUESTION: Return an array without any values, but of a given length.
 * 
 * Note:
 * The length value will always be greater than 0.
 * This exercise is to showcase a behaviour of a certain javascript feature, so as to use 
 * it carefully.
 * Note the output generated by the function.
 * 
 * INPUT:
 *  const length = 12;
 * 
 * OUTPUT:
 *  ,,,,,,,,,,,
 */

/**
 * Returns an array of given length
 *
 * @param {number} length length of the expected array
 * @returns {Array} result.
 */
const createArray = (length) => {
    return new Array(length);
}

function checkTestCase(num, length){
    const result = createArray(length);
    console.log(`Test Case - ${num}`);
    console.log(`${result}`);
}

checkTestCase(1, 12);
checkTestCase(2, 20);